fixtures:
  repositories:
    stdlib:
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: "4.13.1"
    ntp: "https://github.com/puppetlabs/puppetlabs-ntp.git"
    mysql: "https://github.com/puppetlabs/puppetlabs-mysql.git"
    lvm: "https://github.com/puppetlabs/puppetlabs-lvm.git"

  symlinks:
    profile_mysql: "#{source_dir}"
