fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"

# profile module layout, default include ntp module
    ntp: "https://github.com/puppetlabs/puppetlabs-ntp.git"
    mysql: "https://github.com/puppetlabs/puppetlabs-mysql.git"

  symlinks:
    profile_mysql: "#{source_dir}"
